version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - jbhannah
  ignore:
  - dependency-name: react-hook-form
    versions:
    - 6.14.2
    - 6.15.0
    - 6.15.1
    - 6.15.2
    - 6.15.3
    - 6.15.4
    - 6.15.5
    - 6.15.7
    - 7.0.0
    - 7.0.1
    - 7.0.2
    - 7.0.3
    - 7.0.4
    - 7.0.5
    - 7.0.6
    - 7.0.7
    - 7.1.0
    - 7.2.1
    - 7.2.3
    - 7.3.0
    - 7.3.1
    - 7.3.2
    - 7.3.3
    - 7.3.4
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: "@types/jest"
    versions:
    - 26.0.20
    - 26.0.21
    - 26.0.22
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
